http:
  middlewares:

    nas-nextcloud:
      chain:
        middlewares:
          - nas-nextcloud-prefix
          - nas-nextcloud-redirect-regex
          - nas-nextcloud-headers

    nas-nextcloud-prefix:
      replacePathRegex:
        regex: '^/nextcloud(\/|(.*))'
        replacement: "^/nextcloud/${1}"

    nas-nextcloud-redirect-regex:
      redirectRegex:
        permanent: true
        regex: '^(http|https)\:\/\/(\[[\w:.]+\]|[\w\._-]+)/.well-known/(card|cal)dav'
        replacement: "${1}://${2}/remote.php/dav/"

    nas-nextcloud-headers:
      headers:
        customRequestHeaders:
          Referrer-Policy: "no-referrer"
          X-Content-Type-Options: "nosniff"
          X-Download-Options: "noopen"
          X-Frame-Options: "SAMEORIGIN"
          X-Permitted-Cross-Domain-Policies: "none"
          X-Robots-Tag: "none"
          X-XSS-Protection: "1; mode=block"
        customResponseHeaders:
          Referrer-Policy: "no-referrer"
          X-Content-Type-Options: "nosniff"
          X-Download-Options: "noopen"
          X-Frame-Options: "SAMEORIGIN"
          X-Permitted-Cross-Domain-Policies: "none"
          X-Robots-Tag: "none"
          X-XSS-Protection: "1; mode=block"

