version: "3.5"

services:

  nextcloud-db-test:
    image: mariadb
    container_name: nextcloud-db-test
    restart: on-failure
    secrets:
      - mysql_nextcloud_password
    networks:
      - back_end
    depends_on:
      - nextcloud-db
    command: /bin/bash -c "mysql -v -unextcloud -p`cat /run/secrets/mysql_nextcloud_password` --protocol=tcp --host=nextcloud-db --execute='show databases;'"
    #command: /bin/bash -c "mysql -v -unextcloud --protocol=tcp --host=mysql-db --execute='show databases;'"
