---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "NAS Navigator"
subtitle: "Homepage"
#logo: "logo.png"
icon: "fas fa-home"

header: true
footer: |
  <p> Fork me on
    <a href="https://github.com/zcchen/nas-docker-compose">
      <i class="fab fa-github-alt"> </i>
      zcchen/nas-docker-compose
    </a>
  </p>
# set false if you want to hide it.

#connectivityCheck: true

# Optional navbar
links:
  - name: "home"
    icon: "fas fa-home"
    url: ""
    target: ""
  - name: "中文"
    #icon: "fab fa-github"
    url: "#zh"
    target: ""
  - name: "English"
    #icon: "fab fa-github"
    url: "#en"
    target: ""

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

